export const GET_RECIPES_REQUEST="GET_RECIPES_REQUEST"
export const GET_RECIPES_SUCESS="GET_RECIPES_SUCESS"
export const GET_RECIPES_FAIL="GET_RECIPES_FAIL"

export const ADD_RECIPES_REQUEST="ADD_RECIPES_REQUEST"
export const ADD_RECIPES_SUCESS="ADD_RECIPES_SUCESS"
export const ADD_RECIPES_FAIL="ADD_RECIPES_FAIL"

export const MY_RECIPE_GET_RECIPES_REQUEST="MY_RECIPE_GET_RECIPES_REQUEST"
export const MY_RECIPE_GET_RECIPES_SUCESS="MY_RECIPE_GET_RECIPES_SUCESS"
export const MY_RECIPE_GET_RECIPES_FAIL="MY_RECIPE_GET_RECIPES_FAIL"

export const EREASEDATA = "EREASEDATA"