export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'


export const LOGIN_REQUEST_GITHUB = 'LOGIN_REQUEST_GITHUB'
export const LOGIN_FAIL_GITHUB = 'LOGIN_FAIL'
export const LOGIN_SUCCESS_GITHUB = 'LOGIN_SUCCESS_GITHUB'

export const LOGOUT = "LOGOUT";